-- Farmers

-- !Ups

create table country (
  id                            serial,
  code                          varchar(2) not null,
  name                          varchar not null,
  constraint name_unique unique (name),
  constraint pk_country primary key (id)
);

create table farmer (
  id                            serial,
  first_name                    varchar not null,
  last_name                     varchar not null,
  tax_number                    varchar,
  country_id                    int not null,
  constraint country_tax_number unique (tax_number, country_id),
  constraint pk_farmer primary key (id)
);

alter table Farmer add constraint fk_farmer_country_id
  foreign key (country_id) references country (id) on delete restrict on update restrict;

create index ix_farmer_name on farmer (last_name);

INSERT INTO country VALUES
  (DEFAULT, 'AW', 'Aruba'),
  (DEFAULT, 'AG', 'Antigua and Barbuda'),
  (DEFAULT, 'AE', 'United Arab Emirates'),
  (DEFAULT, 'AF', 'Afghanistan'),
  (DEFAULT, 'DZ', 'Algeria'),
  (DEFAULT, 'AZ', 'Azerbaijan'),
  (DEFAULT, 'AL', 'Albania'),
  (DEFAULT, 'AM', 'Armenia'),
  (DEFAULT, 'AD', 'Andorra'),
  (DEFAULT, 'AO', 'Angola'),
  (DEFAULT, 'AS', 'American Samoa'),
  (DEFAULT, 'AR', 'Argentina'),
  (DEFAULT, 'AU', 'Australia'),
  (DEFAULT, '-', 'Ashmore and Cartier Islands'),
  (DEFAULT, 'AT', 'Austria'),
  (DEFAULT, 'AI', 'Anguilla'),
  (DEFAULT, 'AX', 'Åland Islands'),
  (DEFAULT, 'AQ', 'Antarctica'),
  (DEFAULT, 'BH', 'Bahrain'),
  (DEFAULT, 'BB', 'Barbados'),
  (DEFAULT, 'BW', 'Botswana'),
  (DEFAULT, 'BM', 'Bermuda'),
  (DEFAULT, 'BE', 'Belgium'),
  (DEFAULT, 'BS', 'Bahamas, The'),
  (DEFAULT, 'BD', 'Bangladesh'),
  (DEFAULT, 'BZ', 'Belize'),
  (DEFAULT, 'BA', 'Bosnia and Herzegovina'),
  (DEFAULT, 'BO', 'Bolivia'),
  (DEFAULT, 'MM', 'Myanmar'),
  (DEFAULT, 'BJ', 'Benin'),
  (DEFAULT, 'BY', 'Belarus'),
  (DEFAULT, 'SB', 'Solomon Islands'),
  (DEFAULT, '-', 'Navassa Island'),
  (DEFAULT, 'BR', 'Brazil'),
  (DEFAULT, '-', 'Bassas da India'),
  (DEFAULT, 'BT', 'Bhutan'),
  (DEFAULT, 'BG', 'Bulgaria'),
  (DEFAULT, 'BV', 'Bouvet Island'),
  (DEFAULT, 'BN', 'Brunei'),
  (DEFAULT, 'BI', 'Burundi'),
  (DEFAULT, 'CA', 'Canada'),
  (DEFAULT, 'KH', 'Cambodia'),
  (DEFAULT, 'TD', 'Chad'),
  (DEFAULT, 'LK', 'Sri Lanka'),
  (DEFAULT, 'CG', 'Congo, Republic of the'),
  (DEFAULT, 'CD', 'Congo, Democratic Republic of the'),
  (DEFAULT, 'CN', 'China'),
  (DEFAULT, 'CL', 'Chile'),
  (DEFAULT, 'KY', 'Cayman Islands'),
  (DEFAULT, 'CC', 'Cocos (Keeling) Islands'),
  (DEFAULT, 'CM', 'Cameroon'),
  (DEFAULT, 'KM', 'Comoros'),
  (DEFAULT, 'CO', 'Colombia'),
  (DEFAULT, 'MP', 'Northern Mariana Islands'),
  (DEFAULT, '-', 'Coral Sea Islands'),
  (DEFAULT, 'CR', 'Costa Rica'),
  (DEFAULT, 'CF', 'Central African Republic'),
  (DEFAULT, 'CU', 'Cuba'),
  (DEFAULT, 'CV', 'Cape Verde'),
  (DEFAULT, 'CK', 'Cook Islands'),
  (DEFAULT, 'CY', 'Cyprus'),
  (DEFAULT, 'DK', 'Denmark'),
  (DEFAULT, 'DJ', 'Djibouti'),
  (DEFAULT, 'DM', 'Dominica'),
  (DEFAULT, 'UM', 'Jarvis Island'),
  (DEFAULT, 'DO', 'Dominican Republic'),
  (DEFAULT, '-', 'Dhekelia Sovereign Base Area'),
  (DEFAULT, 'EC', 'Ecuador'),
  (DEFAULT, 'EG', 'Egypt'),
  (DEFAULT, 'IE', 'Ireland'),
  (DEFAULT, 'GQ', 'Equatorial Guinea'),
  (DEFAULT, 'EE', 'Estonia'),
  (DEFAULT, 'ER', 'Eritrea'),
  (DEFAULT, 'SV', 'El Salvador'),
  (DEFAULT, 'ET', 'Ethiopia'),
  (DEFAULT, '-', 'Europa Island'),
  (DEFAULT, 'CZ', 'Czech Republic'),
  (DEFAULT, 'GF', 'French Guiana'),
  (DEFAULT, 'FI', 'Finland'),
  (DEFAULT, 'FJ', 'Fiji'),
  (DEFAULT, 'FK', 'Falkland Islands (Islas Malvinas)'),
  (DEFAULT, 'FM', 'Micronesia, Federated States of'),
  (DEFAULT, 'FO', 'Faroe Islands'),
  (DEFAULT, 'PF', 'French Polynesia'),
  (DEFAULT, 'UM', 'Baker Island'),
  (DEFAULT, 'FR', 'France'),
  (DEFAULT, 'TF', 'French Southern and Antarctic Lands'),
  (DEFAULT, 'GM', 'Gambia, The'),
  (DEFAULT, 'GA', 'Gabon'),
  (DEFAULT, 'GE', 'Georgia'),
  (DEFAULT, 'GH', 'Ghana'),
  (DEFAULT, 'GI', 'Gibraltar'),
  (DEFAULT, 'GD', 'Grenada'),
  (DEFAULT, '-', 'Guernsey'),
  (DEFAULT, 'GL', 'Greenland'),
  (DEFAULT, 'DE', 'Germany'),
  (DEFAULT, '-', 'Glorioso Islands'),
  (DEFAULT, 'GP', 'Guadeloupe'),
  (DEFAULT, 'GU', 'Guam'),
  (DEFAULT, 'GR', 'Greece'),
  (DEFAULT, 'GT', 'Guatemala'),
  (DEFAULT, 'GN', 'Guinea'),
  (DEFAULT, 'GY', 'Guyana'),
  (DEFAULT, '-', 'Gaza Strip'),
  (DEFAULT, 'HT', 'Haiti'),
  (DEFAULT, 'HK', 'Hong Kong'),
  (DEFAULT, 'HM', 'Heard Island and McDonald Islands'),
  (DEFAULT, 'HN', 'Honduras'),
  (DEFAULT, 'UM', 'Howland Island'),
  (DEFAULT, 'HR', 'Croatia'),
  (DEFAULT, 'HU', 'Hungary'),
  (DEFAULT, 'IS', 'Iceland'),
  (DEFAULT, 'ID', 'Indonesia'),
  (DEFAULT, 'IM', 'Isle of Man'),
  (DEFAULT, 'IN', 'India'),
  (DEFAULT, 'IO', 'British Indian Ocean Territory'),
  (DEFAULT, '-', 'Clipperton Island'),
  (DEFAULT, 'IR', 'Iran'),
  (DEFAULT, 'IL', 'Israel'),
  (DEFAULT, 'IT', 'Italy'),
  (DEFAULT, 'CI', 'Cote d''Ivoire'),
  (DEFAULT, 'IQ', 'Iraq'),
  (DEFAULT, 'JP', 'Japan'),
  (DEFAULT, 'JE', 'Jersey'),
  (DEFAULT, 'JM', 'Jamaica'),
  (DEFAULT, 'SJ', 'Jan Mayen'),
  (DEFAULT, 'JO', 'Jordan'),
  (DEFAULT, 'UM', 'Johnston Atoll'),
  (DEFAULT, '-', 'Juan de Nova Island'),
  (DEFAULT, 'KE', 'Kenya'),
  (DEFAULT, 'KG', 'Kyrgyzstan'),
  (DEFAULT, 'KP', 'Korea, North'),
  (DEFAULT, 'UM', 'Kingman Reef'),
  (DEFAULT, 'KI', 'Kiribati'),
  (DEFAULT, 'KR', 'Korea, South'),
  (DEFAULT, 'CX', 'Christmas Island'),
  (DEFAULT, 'KW', 'Kuwait'),
  (DEFAULT, 'KV', 'Kosovo'),
  (DEFAULT, 'KZ', 'Kazakhstan'),
  (DEFAULT, 'LA', 'Laos'),
  (DEFAULT, 'LB', 'Lebanon'),
  (DEFAULT, 'LV', 'Latvia'),
  (DEFAULT, 'LT', 'Lithuania'),
  (DEFAULT, 'LR', 'Liberia'),
  (DEFAULT, 'SK', 'Slovakia'),
  (DEFAULT, 'UM', 'Palmyra Atoll'),
  (DEFAULT, 'LI', 'Liechtenstein'),
  (DEFAULT, 'LS', 'Lesotho'),
  (DEFAULT, 'LU', 'Luxembourg'),
  (DEFAULT, 'LY', 'Libyan Arab'),
  (DEFAULT, 'MG', 'Madagascar'),
  (DEFAULT, 'MQ', 'Martinique'),
  (DEFAULT, 'MO', 'Macau'),
  (DEFAULT, 'MD', 'Moldova, Republic of'),
  (DEFAULT, 'YT', 'Mayotte'),
  (DEFAULT, 'MN', 'Mongolia'),
  (DEFAULT, 'MS', 'Montserrat'),
  (DEFAULT, 'MW', 'Malawi'),
  (DEFAULT, 'ME', 'Montenegro'),
  (DEFAULT, 'MK', 'The Former Yugoslav Republic of Macedonia'),
  (DEFAULT, 'ML', 'Mali'),
  (DEFAULT, 'MC', 'Monaco'),
  (DEFAULT, 'MA', 'Morocco'),
  (DEFAULT, 'MU', 'Mauritius'),
  (DEFAULT, 'UM', 'Midway Islands'),
  (DEFAULT, 'MR', 'Mauritania'),
  (DEFAULT, 'MT', 'Malta'),
  (DEFAULT, 'OM', 'Oman'),
  (DEFAULT, 'MV', 'Maldives'),
  (DEFAULT, 'MX', 'Mexico'),
  (DEFAULT, 'MY', 'Malaysia'),
  (DEFAULT, 'MZ', 'Mozambique'),
  (DEFAULT, 'NC', 'New Caledonia'),
  (DEFAULT, 'NU', 'Niue'),
  (DEFAULT, 'NF', 'Norfolk Island'),
  (DEFAULT, 'NE', 'Niger'),
  (DEFAULT, 'VU', 'Vanuatu'),
  (DEFAULT, 'NG', 'Nigeria'),
  (DEFAULT, 'NL', 'Netherlands'),
  (DEFAULT, '-', 'No Man''s Land'),
  (DEFAULT, 'NO', 'Norway'),
  (DEFAULT, 'NP', 'Nepal'),
  (DEFAULT, 'NR', 'Nauru'),
  (DEFAULT, 'SR', 'Suriname'),
  (DEFAULT, 'AN', 'Netherlands Antilles'),
  (DEFAULT, 'NI', 'Nicaragua'),
  (DEFAULT, 'NZ', 'New Zealand'),
  (DEFAULT, 'PY', 'Paraguay'),
  (DEFAULT, 'PN', 'Pitcairn Islands'),
  (DEFAULT, 'PE', 'Peru'),
  (DEFAULT, '-', 'Paracel Islands'),
  (DEFAULT, '-', 'Spratly Islands'),
  (DEFAULT, 'PK', 'Pakistan'),
  (DEFAULT, 'PL', 'Poland'),
  (DEFAULT, 'PA', 'Panama'),
  (DEFAULT, 'PT', 'Portugal'),
  (DEFAULT, 'PG', 'Papua New Guinea'),
  (DEFAULT, 'PW', 'Palau'),
  (DEFAULT, 'GW', 'Guinea-Bissau'),
  (DEFAULT, 'QA', 'Qatar'),
  (DEFAULT, 'RE', 'Reunion'),
  (DEFAULT, 'RS', 'Serbia'),
  (DEFAULT, 'MH', 'Marshall Islands'),
  (DEFAULT, 'MF', 'Saint Martin'),
  (DEFAULT, 'RO', 'Romania'),
  (DEFAULT, 'PH', 'Philippines'),
  (DEFAULT, 'PR', 'Puerto Rico'),
  (DEFAULT, 'RU', 'Russia'),
  (DEFAULT, 'RW', 'Rwanda'),
  (DEFAULT, 'SA', 'Saudi Arabia'),
  (DEFAULT, 'PM', 'Saint Pierre and Miquelon'),
  (DEFAULT, 'KN', 'Saint Kitts and Nevis'),
  (DEFAULT, 'SC', 'Seychelles'),
  (DEFAULT, 'ZA', 'South Africa'),
  (DEFAULT, 'SN', 'Senegal'),
  (DEFAULT, 'SH', 'Saint Helena'),
  (DEFAULT, 'SI', 'Slovenia'),
  (DEFAULT, 'SL', 'Sierra Leone'),
  (DEFAULT, 'SM', 'San Marino'),
  (DEFAULT, 'SG', 'Singapore'),
  (DEFAULT, 'SO', 'Somalia'),
  (DEFAULT, 'ES', 'Spain'),
  (DEFAULT, 'LC', 'Saint Lucia'),
  (DEFAULT, 'SD', 'Sudan'),
  (DEFAULT, 'SJ', 'Svalbard'),
  (DEFAULT, 'SE', 'Sweden'),
  (DEFAULT, 'GS', 'South Georgia and the Islands'),
  (DEFAULT, 'SY', 'Syrian Arab Republic'),
  (DEFAULT, 'CH', 'Switzerland'),
  (DEFAULT, 'TT', 'Trinidad and Tobago'),
  (DEFAULT, '-', 'Tromelin Island'),
  (DEFAULT, 'TH', 'Thailand'),
  (DEFAULT, 'TJ', 'Tajikistan'),
  (DEFAULT, 'TC', 'Turks and Caicos Islands'),
  (DEFAULT, 'TK', 'Tokelau'),
  (DEFAULT, 'TO', 'Tonga'),
  (DEFAULT, 'TG', 'Togo'),
  (DEFAULT, 'ST', 'Sao Tome and Principe'),
  (DEFAULT, 'TN', 'Tunisia'),
  (DEFAULT, 'TL', 'East Timor'),
  (DEFAULT, 'TR', 'Turkey'),
  (DEFAULT, 'TV', 'Tuvalu'),
  (DEFAULT, 'TW', 'Taiwan'),
  (DEFAULT, 'TM', 'Turkmenistan'),
  (DEFAULT, 'TZ', 'Tanzania, United Republic of'),
  (DEFAULT, 'UG', 'Uganda'),
  (DEFAULT, 'GB', 'United Kingdom'),
  (DEFAULT, 'UA', 'Ukraine'),
  (DEFAULT, 'US', 'United States'),
  (DEFAULT, 'BF', 'Burkina Faso'),
  (DEFAULT, 'UY', 'Uruguay'),
  (DEFAULT, 'UZ', 'Uzbekistan'),
  (DEFAULT, 'VC', 'Saint Vincent and the Grenadines'),
  (DEFAULT, 'VE', 'Venezuela'),
  (DEFAULT, 'VG', 'British Virgin Islands'),
  (DEFAULT, 'VN', 'Vietnam'),
  (DEFAULT, 'VI', 'Virgin Islands (US)'),
  (DEFAULT, 'VA', 'Holy See (Vatican City)'),
  (DEFAULT, 'NA', 'Namibia'),
  (DEFAULT, '-', 'West Bank'),
  (DEFAULT, 'WF', 'Wallis and Futuna'),
  (DEFAULT, 'EH', 'Western Sahara'),
  (DEFAULT, 'UM', 'Wake Island'),
  (DEFAULT, 'WS', 'Samoa'),
  (DEFAULT, 'SZ', 'Swaziland'),
  (DEFAULT, 'CS', 'Serbia and Montenegro'),
  (DEFAULT, 'YE', 'Yemen'),
  (DEFAULT, 'ZM', 'Zambia'),
  (DEFAULT, 'ZW', 'Zimbabwe');

-- !Downs

alter table if exists Farmer drop constraint if exists fk_farmer_country_id;
drop index if exists ix_farmer_name;

DROP TABLE farmer;
DROP TABLE country;